task :default => 'morning:turn_off_alarm'

namespace :morning do
  desc "Turn off the alarm"
  task :turn_off_alarm do
    puts "Turned off the alarm clock"
  end

  desc "Spruce up"
  task :groom do
    puts "Brushed teeth"
    puts "Showered"
    puts "Micturated"
  end

  desc "Caffeinate"
  task :make_coffee do
    cups = ENV["COFFEE_CUPS"] || 2
    puts "Made #{cups} cups of coffee"
  end

  desc "I hate that dog"
  task :walk_dog do
    puts "Dog walked"
  end

  desc "Do all the morning things"
  task :get_ready => [:turn_off_alarm, :groom, :make_coffee, :walk_dog] do
    puts "Ready for mindless wage slavery"
  end
end

namespace :morning do
  task :groom do
    puts "Styled hair"
  end
end
